### ISSUE TITLE
listfiles.py different output as callrest.py -e /folders/folders/uri/members

### ISSUE THREAD

**Issue by steffenviya** [sassoftware/pyviyatools#22] opened 2019-09-10 14:30 UTC
[xxx@xxx test]$ /sas/admin/pyviyatools/listfiles.py -p /folders/folders/735c7c67-8830-43e7-a96f-e0bc5347cb93 -o csv
id ,name ,contentType ,documentType ,createdBy ,modifiedTimeStamp ,size ,parentUri
"6c5afad3-38ca-4834-b356-4abb416ed5a0","FileShareImport.sas","application/octet-stream","None","L0508612","2019-09-03T15:39:11.263Z","194","/folders/folders/735c7c67-8830-43e7-a96f-e0bc5347cb93"

List only 1 file in folder

[xxx@xxx test]$ /sas/admin/pyviyatools/callrestapi.py -e /folders/folders/735c7c67-8830-43e7-a96f-e0bc5347cb93/members -m get -o csv
id ,name ,type ,description ,creationTimeStamp ,modifiedTimeStamp
"0259a1c4-7197-48c2-844e-bc26b9a7d45b","FileResource1562770146781","child","None","2019-07-10T14:49:06.781Z","2019-09-03T15:39:11.227Z"
"5b87b8e5-18ae-4240-b1d4-f85d55a8389c","FileShareImport.sas","child","","2019-05-09T10:11:23.664Z","2019-09-03T15:39:11.263Z"
"425e80a2-9079-4580-9729-d909ec52995b","FileShareTest.csv","child","None","2019-07-10T14:49:39.398Z","2019-09-03T15:39:11.298Z"
"f88dbb68-4602-43b3-be8a-bdc15a0729ef","test.csv","child","None","2019-05-09T10:05:02.076Z","2019-09-03T15:39:26.188Z"

List 4 files in folder.

**Comment by gerrynelson63** [comment] 2019-09-20 19:15
The -u parameter is the parenturi of the service. Listfiles was designed really to process files that are not displayed in folders, but that are managed by a service. The parenturi is the uri of a service. That being said, I realize that was not clear, and it would be useful to be able to list files in a folder. I have update the tool, the draft update is in the branch  update_filetools. I added a parameter -pf which allows you to pass a parent folder as an alternative to a parent service uri. Please take a look and I will merge it into master once you review it. Thanks.

**Comment by dwstern** [comment] 2022-08-24 16:03
Looks like this was merged in pull request 24 https://github.com/sassoftware/pyviyatools/pull/24. Closing.

**Closed by dwstern** 2022-08-24 16:03 UTC
